// ─────────────────────────────────────────────────────────────────────────────
// Pri Learning · Generator registry — one lazily-loaded bank per year/stream.
// The whole Years 7–12 bank is ~536 kB of source and a student practises inside
// two or three of its files, so each year and stream module is its own dynamic
// chunk instead of a static import. Banks are pulled in by the API layer before
// a request reaches the backend; `generateQuestion` itself stays synchronous so
// the local backend keeps the exact call signature it has always had.
// ─────────────────────────────────────────────────────────────────────────────
import { makeRng } from '../qhelpers.js';
import { dotpointById, dotpointAt, formDotpoints } from '../curriculum.js';

// ── Banks ────────────────────────────────────────────────────────────────────

const BANKS = {
  year7: () => import('./year7.js').then(m => m.year7),
  year8: () => import('./year8.js').then(m => m.year8),
  year9: () => import('./year9.js').then(m => m.year9),
  year10: () => import('./year10.js').then(m => m.year10),
  year11: () => import('./year11.js').then(m => m.year11),
  year12: () => import('./year12.js').then(m => m.year12),
  'streams-standard': () => import('./streams-standard.js').then(m => m.streamsStandard),
  'streams-ext': () => import('./streams-ext.js').then(m => m.streamsExt)
};

// Subtopic ids are namespaced by the bank that authors them: y9-surds lives in
// year9, ms12-loans in streams-standard, mex-complex in streams-ext.
const BANK_OF = {
  y7: 'year7', y8: 'year8', y9: 'year9', y10: 'year10', y11: 'year11', y12: 'year12',
  ms11: 'streams-standard', ms12: 'streams-standard',
  me11: 'streams-ext', me12: 'streams-ext', mex: 'streams-ext'
};

/** Holds the generators of every bank loaded so far, keyed by subtopic id. */
export const GENERATORS = {};

const loaded = new Set();
const inflight = new Map();

/** The bank a subtopic id belongs to, or null if the id names no bank. */
export function bankOf(subtopicId) {
  return BANK_OF[String(subtopicId ?? '').split('-')[0]] || null;
}

function loadBank(name) {
  if (loaded.has(name)) return Promise.resolve();
  let job = inflight.get(name);
  if (!job) {
    job = BANKS[name]().then(bank => {
      Object.assign(GENERATORS, bank);
      loaded.add(name);
      inflight.delete(name);
    }, err => {
      inflight.delete(name);
      throw err;
    });
    inflight.set(name, job);
  }
  return job;
}

/** Load the named banks; unknown names are ignored. Resolves once all are in. */
export function loadBanks(names) {
  return Promise.all([...new Set(names)].filter(n => BANKS[n]).map(loadBank)).then(() => { });
}

/** Load whichever banks author the given subtopic ids. */
export function loadBanksFor(subtopicIds) {
  return loadBanks(subtopicIds.map(bankOf).filter(Boolean));
}

/** Load every bank — for callers that can reach any year, such as the demo seed. */
export function loadAllBanks() {
  return loadBanks(Object.keys(BANKS));
}

// ── Dot-point resolution ─────────────────────────────────────────────────────
// A question is generated by one authored form, and a form exercises one or
// more of its subtopic's dot points. Three declarations are consulted, most
// specific first:
//
//   1. the payload — a generator may return `dotpoint` / `dotpoints` for the
//      branch it just took, which is the only way to be exact about a form that
//      asks about perimeter on one branch and area on the next;
//   2. the generator function — `gen.dotpoints = { 1: [0], 2: [1] }` lets a
//      bank declare per difficulty without touching every return statement;
//   3. DOTPOINT_FORMS in curriculum.js — the registry-side table, which knows a
//      cell but cannot know a branch.
//
// Ordinals are 0-based within the subtopic; ids and `subtopic#slug` keys are
// accepted too, so a bank can write whichever reads better at the call site.

/** Normalise one declared reference to a dot point of `subtopicId`, or null. */
function toDotpoint(subtopicId, ref) {
  if (ref == null) return null;
  if (typeof ref === 'number') return dotpointAt(subtopicId, ref);
  const dp = dotpointById(ref);
  return dp && dp.subtopic === subtopicId ? dp : null;
}

function declaredOn(source, subtopicId) {
  if (!source) return null;
  const raw = source.dotpoints ?? source.dotpoint;
  if (raw == null) return null;
  const list = (Array.isArray(raw) ? raw : [raw]).map(r => toDotpoint(subtopicId, r)).filter(Boolean);
  return list.length ? list : null;
}

/** The dot points a generated payload exercises, and where that was declared. */
function dotpointsOf(gen, subtopicId, difficulty, payload) {
  const fromPayload = declaredOn(payload, subtopicId);
  if (fromPayload) return { list: fromPayload, source: 'bank' };
  const perDifficulty = gen?.dotpoints?.[difficulty];
  const fromGenerator = perDifficulty == null ? null : declaredOn({ dotpoints: perDifficulty }, subtopicId);
  if (fromGenerator) return { list: fromGenerator, source: 'bank' };
  const fromRegistry = formDotpoints(subtopicId, difficulty);
  return { list: fromRegistry, source: fromRegistry.length ? 'registry' : null };
}

/**
 * The difficulty to generate at when a dot point has been asked for. A dot
 * point is only reachable through the difficulties whose form exercises it, so
 * a requested difficulty that cannot deliver it is snapped to the nearest one
 * that can (ties go to the easier). With no difficulty asked for, the seed
 * chooses — through its own rng, so the generator's stream is untouched and a
 * three-argument call still reproduces its question exactly.
 */
function difficultyFor(dp, difficulty, seed) {
  const forms = dp.forms;
  if (!forms.length) return null;
  if (difficulty == null) return forms[Math.floor(makeRng((seed ^ 0x5bf03635) >>> 0)() * forms.length)];
  const d = Math.min(4, Math.max(1, difficulty | 0));
  if (forms.includes(d)) return d;
  return forms.reduce((best, f) => {
    const gap = Math.abs(f - d), bestGap = Math.abs(best - d);
    return gap < bestGap || (gap === bestGap && f < best) ? f : best;
  });
}

// ── Generation ───────────────────────────────────────────────────────────────

/**
 * Generate a question for a subtopic at a difficulty (1–4).
 * Returns { seed, subtopic, difficulty, dotpoint, dotpoints, dotpointSource,
 * ...payload }.
 *
 * `dotpoints` is every dot point the question exercises, as ids; `dotpoint` is
 * the single id when — and only when — the question can honestly be pinned to
 * one, and null otherwise, so a caller is never handed a dot point the question
 * only half exercises. `dotpointSource` records which declaration produced them
 * ('bank', 'registry') or null when nothing stands behind the cell.
 *
 * Pass `dotpointId` to REQUEST one: the difficulty is then resolved to one that
 * exercises it, and the result carries `dotpointRequested` plus `dotpointExact`
 * — false when no authored form exercises that dot point and the question is a
 * subtopic-level stand-in. Callers can test for that up front with
 * `difficultiesForDotpoint` in curriculum.js.
 *
 * The three-argument signature is unchanged: same rng draws, same question for
 * the same seed.
 *
 * Throws with `bankMissing` set when the subtopic is real but its bank has not
 * been loaded yet, which lets the API layer fetch that one bank and re-run the
 * request. Nothing is written before this point in any route that calls it.
 */
export function generateQuestion(subtopicId, difficulty, seed, dotpointId) {
  const gen = GENERATORS[subtopicId];
  if (!gen) {
    const bank = bankOf(subtopicId);
    if (bank && !loaded.has(bank)) {
      throw Object.assign(new Error(`Question bank "${bank}" is not loaded`), { bankMissing: true, bank, subtopic: subtopicId });
    }
    throw new Error(`No generator for subtopic ${subtopicId}`);
  }
  const s = seed ?? Math.floor(Math.random() * 2 ** 31);
  let requested = null;
  let want = difficulty;
  if (dotpointId != null) {
    requested = toDotpoint(subtopicId, dotpointId);
    if (!requested) throw new Error(`No dot point ${dotpointId} in subtopic ${subtopicId}`);
    want = difficultyFor(requested, difficulty, s) ?? difficulty;
  }
  const rng = makeRng(s);
  const d = Math.min(4, Math.max(1, want | 0));
  const payload = gen(rng, d);
  const q = { seed: s, subtopic: subtopicId, difficulty: d, ...payload };
  const { list, source } = dotpointsOf(gen, subtopicId, d, payload);
  q.dotpoints = list.map(dp => dp.id);
  q.dotpoint = list.length === 1 ? list[0].id : null;
  q.dotpointSource = source;
  if (requested) {
    q.dotpointRequested = requested.id;
    q.dotpointExact = q.dotpoints.includes(requested.id);
  }
  return q;
}
