#!/usr/bin/env python3
"""Pack explicitly approved JEE records into lazy iPad/browser data shards."""
from __future__ import annotations

import argparse
import base64
import gzip
import hashlib
import json
from collections import Counter, defaultdict
from pathlib import Path

from audit import audit, load_jsonl

HERE = Path(__file__).resolve().parent
DEFAULT_MANIFEST = HERE / "source-manifest.json"
DEFAULT_DEST = HERE.parents[1] / "client" / "src" / "engine" / "generators" / "jee-pyq-data"


OFFICIAL_MANIFEST = HERE / "official-sources.json"
_OFFICIAL_DOCS = None


def official_doc(doc_id):
    global _OFFICIAL_DOCS
    if _OFFICIAL_DOCS is None:
        data = json.loads(OFFICIAL_MANIFEST.read_text(encoding="utf-8")) if OFFICIAL_MANIFEST.exists() else {"documents": []}
        _OFFICIAL_DOCS = {d["id"]: d for d in data["documents"]}
    return _OFFICIAL_DOCS.get(doc_id) or {}


def compact_official(row):
    src, routing, exam, review = row["source"], row["routing"], row["exam"], row["review"]
    key_doc = official_doc(src.get("keyDocumentId"))
    return {
        "id": row["id"],
        "chapterId": routing["targetChapter"],
        "sourceChapter": None,
        "sourceTopic": "",
        "sourceTopicNumber": None,
        "sourceQuestionNumber": src["questionNumber"],
        "sourcePage": src["page"],
        "sourcePdfPage": src["page"],
        "examYear": exam.get("year"),
        "examTrack": exam["track"],
        "difficulty": row["difficulty"],
        "answerType": row["answerType"],
        "prompt": row["prompt"],
        "answer": row.get("answer"),
        "mcqOptions": row.get("mcqOptions"),
        "hints": row.get("hints") or [],
        "steps": row["steps"],
        "official": {
            "authority": src.get("authority"),
            "documentId": src["documentId"],
            "url": src["url"],
            "archivedAt": src.get("archivedAt"),
            "keyUrl": src.get("keyUrl"),
            "keyDocumentId": src.get("keyDocumentId"),
            "keyArchivedAt": key_doc.get("archivedAt"),
            "paper": exam.get("paper"),
            "session": exam.get("session"),
            "shift": exam.get("shift"),
            "section": src.get("section"),
        },
        "review": {
            "reviewedBy": review["reviewedBy"],
            "reviewedAt": review["reviewedAt"],
            "tier": review.get("tier"),
        },
    }


def compact_record(row):
    if (row.get("source") or {}).get("kind") == "official":
        return compact_official(row)
    src, routing, exam = row["source"], row["routing"], row["exam"]
    return {
        "id": row["id"],
        "chapterId": routing["targetChapter"],
        "sourceChapter": src["sourceChapter"],
        "sourceTopic": src.get("sourceTopic") or "",
        "sourceTopicNumber": src.get("sourceTopicNumber"),
        "sourceQuestionNumber": src["sourceQuestionNumber"],
        "sourcePage": src["sourcePage"],
        "sourcePdfPage": src["sourcePdfPage"],
        "examYear": exam.get("year"),
        "examTrack": exam["track"],
        "difficulty": row["difficulty"],
        "answerType": row["answerType"],
        "prompt": row["prompt"],
        "answer": row.get("answer"),
        "mcqOptions": row.get("mcqOptions"),
        "hints": row.get("hints") or [],
        "steps": row["steps"],
        "review": {
            "reviewedBy": row["review"]["reviewedBy"],
            "reviewedAt": row["review"]["reviewedAt"],
        },
    }


def chunks(text, max_chars):
    return [text[i:i + max_chars] for i in range(0, len(text), max_chars)] or [""]


def emit_catalog(dest: Path, part_files, coverage, meta):
    lines = [
        "// GENERATED by tools/jee-question-department/pack.py — do not hand edit.",
        "// Each shard is a tiny ES module exporting its base64 text, loaded by a",
        "// dynamic import: Vite code-splits it into a local, cacheable chunk (no",
        "// fetch/XHR) and plain Node test suites can load it too. It stays lazy",
        "// offline use but remains lazy until its reviewed JEE chapter is opened.",
        "export const JEE_PYQ_PARTS = Object.freeze({",
    ]
    for part in sorted(part_files):
        loaders = ", ".join(
            f"() => import('./{name}').then(module => module.default)"
            for name in part_files[part]
        )
        lines.append(f"  {json.dumps(part)}: Object.freeze([{loaders}]),")
    lines += [
        "});",
        "",
        "export const JEE_PYQ_COVERAGE = Object.freeze(" + json.dumps(coverage, sort_keys=True, separators=(",", ":")) + ");",
        "export const JEE_PYQ_META = Object.freeze(" + json.dumps(meta, sort_keys=True, separators=(",", ":")) + ");",
        "",
    ]
    (dest / "catalog.js").write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description="Pack approved JEE questions into lazy data assets")
    ap.add_argument("approved", type=Path)
    ap.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    ap.add_argument("--dest", type=Path, default=DEFAULT_DEST)
    ap.add_argument("--max-base64-chars", type=int, default=220_000)
    args = ap.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    rows = load_jsonl(args.approved)
    summary, errors, warnings = audit(rows, manifest, publish=True)
    if errors:
        print(json.dumps({"summary": summary, "errors": errors, "warnings": warnings}, indent=2))
        raise SystemExit("Publish audit failed; no data assets were written.")

    approved = [compact_record(r) for r in rows if r.get("status") == "approved"]
    by_part = defaultdict(list)
    chapter_to_parts = defaultdict(set)
    for row, original in zip(approved, [r for r in rows if r.get("status") == "approved"]):
        part = original["routing"]["part"]
        by_part[part].append(row)
        gid = f"{row['examTrack']}-{row['chapterId']}"
        chapter_to_parts[gid].add(part)

    args.dest.mkdir(parents=True, exist_ok=True)
    # Remove only generated shards. Keep README and hand-authored catalog fallback safe.
    for old in list(args.dest.glob("*.b64")) + list(args.dest.glob("*-[0-9][0-9].js")):
        old.unlink()

    part_files = {}
    sha = hashlib.sha256()
    for part, records in sorted(by_part.items()):
        records.sort(key=lambda r: (r["chapterId"], r.get("examYear") or 0, r["sourcePage"], r["sourceQuestionNumber"]))
        raw = json.dumps(records, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        sha.update(raw)
        encoded = base64.b64encode(gzip.compress(raw, compresslevel=9, mtime=0)).decode("ascii")
        names = []
        for i, piece in enumerate(chunks(encoded, args.max_base64_chars)):
            name = f"{part}-{i:02d}.js"
            (args.dest / name).write_text("// GENERATED by tools/jee-question-department/pack.py - do not hand edit.\n"
                                          f"export default {json.dumps(piece)};\n", encoding="ascii")
            names.append(name)
        part_files[part] = names

    meta = {
        "schemaVersion": 1,
        "records": len(approved),
        "parts": len(part_files),
        "sha256": sha.hexdigest(),
        "tracks": dict(Counter(r["examTrack"] for r in approved)),
        "reviewTiers": dict(Counter((r.get("review") or {}).get("tier") or "human" for r in approved)),
        "answerTypes": dict(Counter(r["answerType"] for r in approved)),
    }
    coverage = {gid: sorted(parts) for gid, parts in sorted(chapter_to_parts.items())}
    emit_catalog(args.dest, part_files, coverage, meta)
    print(json.dumps({"dest": str(args.dest), "meta": meta, "files": part_files}, indent=2))


if __name__ == "__main__":
    main()
