#!/usr/bin/env python3
"""Pack explicitly approved JEE records into lazy iPad/browser data shards."""
from __future__ import annotations

import argparse
import base64
import gzip
import hashlib
import json
from collections import Counter, defaultdict
from pathlib import Path

from audit import audit, load_jsonl

HERE = Path(__file__).resolve().parent
DEFAULT_MANIFEST = HERE / "source-manifest.json"
DEFAULT_DEST = HERE.parents[1] / "client" / "src" / "engine" / "generators" / "jee-pyq-data"


def compact_record(row):
    src, routing, exam = row["source"], row["routing"], row["exam"]
    return {
        "id": row["id"],
        "chapterId": routing["targetChapter"],
        "sourceChapter": src["sourceChapter"],
        "sourceTopic": src.get("sourceTopic") or "",
        "sourceTopicNumber": src.get("sourceTopicNumber"),
        "sourceQuestionNumber": src["sourceQuestionNumber"],
        "sourcePage": src["sourcePage"],
        "sourcePdfPage": src["sourcePdfPage"],
        "examYear": exam.get("year"),
        "examTrack": exam["track"],
        "difficulty": row["difficulty"],
        "answerType": row["answerType"],
        "prompt": row["prompt"],
        "answer": row.get("answer"),
        "mcqOptions": row.get("mcqOptions"),
        "hints": row.get("hints") or [],
        "steps": row["steps"],
        "review": {
            "reviewedBy": row["review"]["reviewedBy"],
            "reviewedAt": row["review"]["reviewedAt"],
        },
    }


def chunks(text, max_chars):
    return [text[i:i + max_chars] for i in range(0, len(text), max_chars)] or [""]


def emit_catalog(dest: Path, part_files, coverage, meta):
    lines = [
        "// GENERATED by tools/jee-question-department/pack.py — do not hand edit.",
        "// Each shard is a Vite ?raw dynamic import: it is bundled/cacheable for",
        "// offline use but remains lazy until its reviewed JEE chapter is opened.",
        "export const JEE_PYQ_PARTS = Object.freeze({",
    ]
    for part in sorted(part_files):
        loaders = ", ".join(
            f"() => import('./{name}?raw').then(module => module.default)"
            for name in part_files[part]
        )
        lines.append(f"  {json.dumps(part)}: Object.freeze([{loaders}]),")
    lines += [
        "});",
        "",
        "export const JEE_PYQ_COVERAGE = Object.freeze(" + json.dumps(coverage, sort_keys=True, separators=(",", ":")) + ");",
        "export const JEE_PYQ_META = Object.freeze(" + json.dumps(meta, sort_keys=True, separators=(",", ":")) + ");",
        "",
    ]
    (dest / "catalog.js").write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description="Pack approved JEE questions into lazy data assets")
    ap.add_argument("approved", type=Path)
    ap.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    ap.add_argument("--dest", type=Path, default=DEFAULT_DEST)
    ap.add_argument("--max-base64-chars", type=int, default=220_000)
    args = ap.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    rows = load_jsonl(args.approved)
    summary, errors, warnings = audit(rows, manifest, publish=True)
    if errors:
        print(json.dumps({"summary": summary, "errors": errors, "warnings": warnings}, indent=2))
        raise SystemExit("Publish audit failed; no data assets were written.")

    approved = [compact_record(r) for r in rows if r.get("status") == "approved"]
    by_part = defaultdict(list)
    chapter_to_parts = defaultdict(set)
    for row, original in zip(approved, [r for r in rows if r.get("status") == "approved"]):
        part = original["routing"]["part"]
        by_part[part].append(row)
        gid = f"{row['examTrack']}-{row['chapterId']}"
        chapter_to_parts[gid].add(part)

    args.dest.mkdir(parents=True, exist_ok=True)
    # Remove only generated shards. Keep README and hand-authored catalog fallback safe.
    for old in args.dest.glob("*.b64"):
        old.unlink()

    part_files = {}
    sha = hashlib.sha256()
    for part, records in sorted(by_part.items()):
        records.sort(key=lambda r: (r["chapterId"], r.get("examYear") or 0, r["sourcePage"], r["sourceQuestionNumber"]))
        raw = json.dumps(records, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        sha.update(raw)
        encoded = base64.b64encode(gzip.compress(raw, compresslevel=9, mtime=0)).decode("ascii")
        names = []
        for i, piece in enumerate(chunks(encoded, args.max_base64_chars)):
            name = f"{part}-{i:02d}.b64"
            (args.dest / name).write_text(piece + "\n", encoding="ascii")
            names.append(name)
        part_files[part] = names

    meta = {
        "schemaVersion": 1,
        "records": len(approved),
        "parts": len(part_files),
        "sha256": sha.hexdigest(),
        "tracks": dict(Counter(r["examTrack"] for r in approved)),
        "answerTypes": dict(Counter(r["answerType"] for r in approved)),
    }
    coverage = {gid: sorted(parts) for gid, parts in sorted(chapter_to_parts.items())}
    emit_catalog(args.dest, part_files, coverage, meta)
    print(json.dumps({"dest": str(args.dest), "meta": meta, "files": part_files}, indent=2))


if __name__ == "__main__":
    main()
