// ─────────────────────────────────────────────────────────────────────────────
// Builds two files from page.html.part:
//
//   claim.html          full document — the drop-in replacement for GET /c/a2z
//   claim-preview.html  body-only — same page, for publishing as an Artifact so
//                       it can be opened and judged on a real phone
//
// The app's real Computer Modern (KaTeX woff2 from client/node_modules/katex) is
// inlined as data URIs: this page is served standalone and the Artifact iframe
// admits no font host but Google Fonts, which has no Computer Modern.
// ─────────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync } from 'node:fs';

const KATEX = '../../client/node_modules/katex/dist/fonts';

const face = (f, family, weight) =>
  `@font-face{font-family:'${family}';src:url(data:font/woff2;base64,${readFileSync(`${KATEX}/${f}.woff2`).toString('base64')}) format('woff2');font-weight:${weight};font-style:normal;font-display:swap}`;

const fonts = [
  face('KaTeX_Main-Regular', 'KaTeX_Main', 400),
  face('KaTeX_Main-Bold', 'KaTeX_Main', 700),
  face('KaTeX_AMS-Regular', 'KaTeX_AMS', 400),
].join('\n');

const src = readFileSync('page.html.part', 'utf8');
const full = src.replace('__FONTS__', fonts);
writeFileSync('claim.html', full);

const slice = (open, close) => {
  const a = full.indexOf(open), b = full.indexOf(close, a);
  if (a < 0 || b < 0) throw new Error('could not slice ' + open);
  return full.slice(a, b + close.length);
};
const preview = [
  '<title>A2Z Claim Page</title>',
  slice('<style>', '</style>'),
  slice('<main>', '</main>'),
  slice('<script>', '</script>'),
].join('\n');
writeFileSync('claim-preview.html', preview);

const kb = (s) => (s.length / 1024).toFixed(1) + ' KiB';
console.log('claim.html        ', kb(full));
console.log('claim-preview.html', kb(preview));

// ── renderClaimPage() ────────────────────────────────────────────────────────
// The same page as a render function, so wiring it into whatever serves /c/a2z
// is a two-line change rather than a hand-edited template string. The page is
// split into literal chunks around five injection points, and each value is
// escaped for the context it lands in: HTML text, an attribute, or a JS string.
const SLOT = '@@';
const marked = full
  .replace('A2Z A2Z-XXXX-XXXX', SLOT + 'MSG' + SLOT)
  .replace('data-expires-at=""', 'data-expires-at="' + SLOT + 'EXP' + SLOT + '"')
  .replace(
    'var DM = "https://ig.me/m/pri.learning?ref=pri-a2z-qr-2026";',
    'var DM = ' + SLOT + 'DM_JS' + SLOT + ';')
  .replace(
    'href="https://www.instagram.com/pri.learning/" rel="noopener noreferrer"',
    'href="' + SLOT + 'PROFILE' + SLOT + '" rel="noopener noreferrer"')
  .replace(
    "window.location.href = 'https://www.instagram.com/pri.learning/'; return;",
    'window.location.href = ' + SLOT + 'PROFILE_JS' + SLOT + '; return;');

const pieces = marked.split(SLOT);
if (pieces.length !== 11) {
  throw new Error('expected 5 injection points, found ' + ((pieces.length - 1) / 2));
}
const literals = pieces.filter((_, i) => i % 2 === 0);
const slots = pieces.filter((_, i) => i % 2 === 1);

const ESM = `// GENERATED by marketing/a2z-claim-page/build.mjs — do not edit.
// Edit page.html.part and re-run \`node build.mjs\`.
//
//   import { renderClaimPage } from './claim-template.mjs';
//
//   app.get('/c/:campaign', (req, res) => {
//     const { message, expiresAt } = issueVerificationMessage(req);   // your logic
//     res.type('html').send(renderClaimPage({ verificationMessage: message, expiresAt }));
//   });
//
// verificationMessage is required: the exact text the visitor has to send.
// expiresAt is optional (ISO-8601 string or Date). Pass it and the countdown is
// exact; omit it and the page counts 24 hours from the first time that code is
// seen on the device, which is only correct if a fresh code is issued per load.

const LITERALS = ${JSON.stringify(literals)};
const SLOTS = ${JSON.stringify(slots)};

const DEFAULT_DM = 'https://ig.me/m/pri.learning?ref=pri-a2z-qr-2026';
const DEFAULT_PROFILE = 'https://www.instagram.com/pri.learning/';

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

// Safe to drop inside <script>: JSON first, then neutralise the sequences that
// could close the element or start a comment.
function escapeJs(value) {
  return JSON.stringify(String(value))
    .replace(/</g, '\\\\u003c').replace(/>/g, '\\\\u003e').replace(/&/g, '\\\\u0026');
}

function toIso(value) {
  if (!value) return '';
  const d = value instanceof Date ? value : new Date(value);
  return Number.isNaN(d.getTime()) ? '' : d.toISOString();
}

export function renderClaimPage(options = {}) {
  const message = options.verificationMessage;
  if (typeof message !== 'string' || !message.trim()) {
    throw new TypeError('renderClaimPage: verificationMessage is required');
  }
  const values = {
    MSG: escapeHtml(message.trim()),
    EXP: escapeHtml(toIso(options.expiresAt)),
    DM_JS: escapeJs(options.dmUrl || DEFAULT_DM),
    PROFILE: escapeHtml(options.profileUrl || DEFAULT_PROFILE),
    PROFILE_JS: escapeJs(options.profileUrl || DEFAULT_PROFILE),
  };
  let out = LITERALS[0];
  for (let i = 0; i < SLOTS.length; i++) {
    const key = SLOTS[i];
    if (!(key in values)) throw new Error('unknown slot ' + key);
    out += values[key] + LITERALS[i + 1];
  }
  return out;
}

export default renderClaimPage;
`;

writeFileSync('claim-template.mjs', ESM);

// CommonJS twin, for a server that has not moved to ESM.
writeFileSync('claim-template.cjs', ESM
  .replace("import { renderClaimPage } from './claim-template.mjs';",
           "const { renderClaimPage } = require('./claim-template.cjs');")
  .replace('export function renderClaimPage', 'function renderClaimPage')
  .replace('\nexport default renderClaimPage;\n', '\nmodule.exports = { renderClaimPage };\n'));

console.log('claim-template.mjs ', kb(ESM));
console.log('claim-template.cjs ', kb(ESM));
console.log('injection points   ', slots.join(', '));

