// ─────────────────────────────────────────────────────────────────────────────
// Pri Learning · Hindi labels for the skills on the prerequisite graph's edges.
//
// The graph (prerequisites.js) names each edge's skill in English, because the
// mathematics in this app is in English (see the head of
// client/test/i18n-check.mjs). The skill label, though, is interface prose a
// Hindi reader is shown under a traced chain, so it is translated here and the
// placement page uses it when the interface is in Hindi. Keyed by the English
// label; client/test/placement-check.mjs fails if an edge's skill has no entry
// or an entry names a skill no edge carries. Lives beside the graph in the
// on-demand placement chunk, so an English reader never downloads it.
// ─────────────────────────────────────────────────────────────────────────────

export const PREREQ_SKILLS_HI = Object.freeze({
  'order of operations and brackets': 'संक्रियाओं का क्रम और कोष्ठक',
  'writing and simplifying expressions with an unknown': 'अज्ञात राशि वाले व्यंजक लिखना और सरल करना',
  'signed-number arithmetic': 'धन-ऋण संख्याओं का अंकगणित',
  'decimal place value': 'दशमलव का स्थानीय मान',
  'angle relationships on intersecting lines': 'प्रतिच्छेदी रेखाओं पर कोणों के संबंध',
  'triangle sides and angles': 'त्रिभुज की भुजाएँ और कोण',
  'perpendicular and angle reasoning': 'लंब और कोणों पर तर्क',
  'dividing totals to find a mean': 'माध्य के लिए योग को भाग देना',
  'operating on fractions': 'भिन्नों पर संक्रियाएँ',
  'sign rules': 'चिह्नों के नियम',
  'solving an equation by balancing both sides': 'दोनों पक्षों को संतुलित रखकर समीकरण हल करना',
  'clearing fractional coefficients': 'भिन्नात्मक गुणांक हटाना',
  'angle sum of a triangle': 'त्रिभुज के कोणों का योग',
  'angles on parallel lines': 'समांतर रेखाओं पर कोण',
  'reading and summarising data': 'आँकड़े पढ़ना और उनका सार निकालना',
  'fractions of a whole': 'पूर्ण के भिन्नात्मक भाग',
  'prime factorisation': 'अभाज्य गुणनखंडन',
  'number patterns': 'संख्या प्रतिरूप',
  'roots through grouped prime factors': 'अभाज्य गुणनखंडों के समूह से मूल',
  'a fraction or percentage of a quantity': 'किसी राशि का भिन्न या प्रतिशत',
  'multiplying decimals': 'दशमलव संख्याओं का गुणा',
  'simplifying algebraic expressions': 'बीजीय व्यंजकों को सरल करना',
  'sign rules for coefficients': 'गुणांकों के चिह्न नियम',
  'multiplying measurements': 'मापों का गुणा',
  'triangle and quadrilateral shapes': 'त्रिभुज और चतुर्भुज आकृतियाँ',
  'place value and powers of ten': 'स्थानीय मान और दस की घातें',
  'negative numbers': 'ऋणात्मक संख्याएँ',
  'ratios as fractions': 'भिन्न के रूप में अनुपात',
  'scaling quantities': 'राशियों को अनुपात में बढ़ाना-घटाना',
  'expanding products and the standard identities': 'गुणनफलों का प्रसार और मानक सर्वसमिकाएँ',
  'common factors': 'उभयनिष्ठ गुणनखंड',
  'reading data displays': 'आँकड़ों के चित्रण पढ़ना',
  'reading scales': 'पैमाने पढ़ना',
  'plotting ordered pairs': 'क्रमित युग्म आलेखित करना',
  'signed differences': 'चिह्न सहित अंतर',
  'linear expressions in one variable': 'एक चर वाले रैखिक व्यंजक',
  'drawing a graph from a table': 'सारणी से आलेख बनाना',
  'terms and coefficients': 'पद और गुणांक',
  'operating on rational numbers': 'परिमेय संख्याओं पर संक्रियाएँ',
  'square roots': 'वर्गमूल',
  'factor patterns': 'गुणनखंड के प्रतिरूप',
  'expansion identities': 'प्रसार की सर्वसमिकाएँ',
  'polygon angle properties': 'बहुभुज के कोणों के गुण',
  'congruent triangles': 'सर्वांगसम त्रिभुज',
  'area formulae': 'क्षेत्रफल के सूत्र',
  'decimal arithmetic': 'दशमलव अंकगणित',
  'simple probability': 'सरल प्रायिकता',
  'fractions': 'भिन्न',
  'number sequences': 'संख्या अनुक्रम',
  'solving for an unknown term': 'अज्ञात पद ज्ञात करना',
  'powers for geometric terms': 'गुणोत्तर पदों के लिए घातें',
  'prime factorisation, HCF and LCM': 'अभाज्य गुणनखंडन, म.स. और ल.स.',
  'irrational numbers': 'अपरिमेय संख्याएँ',
  'terms, degree and zeroes': 'पद, घात और शून्यक',
  'factorising quadratics': 'द्विघातों का गुणनखंडन',
  'solving a linear equation': 'रैखिक समीकरण हल करना',
  'graphing a linear relation': 'रैखिक संबंध का आलेख',
  'factorising a quadratic': 'द्विघात का गुणनखंडन',
  'surds in the roots': 'मूलों में करणी',
  'the nth term of a progression': 'श्रेढ़ी का n-वाँ पद',
  'solving for an unknown': 'अज्ञात राशि ज्ञात करना',
  'congruence criteria': 'सर्वांगसमता की कसौटियाँ',
  'ratio and proportion': 'अनुपात और समानुपात',
  'distances between points': 'बिंदुओं के बीच दूरियाँ',
  'square roots in the distance formula': 'दूरी सूत्र में वर्गमूल',
  'right-triangle sides through squares and roots': 'वर्ग और वर्गमूल से समकोण त्रिभुज की भुजाएँ',
  'ratios of sides': 'भुजाओं के अनुपात',
  'exact surd values': 'करणी के सटीक मान',
  'similar right triangles share their side ratios': 'समरूप समकोण त्रिभुजों की भुजाओं के अनुपात समान होते हैं',
  'ratios at 30°, 45° and 60°': '30°, 45° और 60° पर अनुपात',
  'chord and radius properties': 'जीवा और त्रिज्या के गुण',
  'circle and sector area': 'वृत्त और त्रिज्यखंड का क्षेत्रफल',
  'a fraction of a full turn': 'पूरे चक्कर का भिन्नात्मक भाग',
  'surface area and volume of solids': 'ठोसों का पृष्ठीय क्षेत्रफल और आयतन',
  'curved areas': 'वक्र क्षेत्रफल',
  'mean, median and mode': 'माध्य, माध्यक और बहुलक',
  'frequency tables': 'बारंबारता सारणियाँ',
  'theoretical probability': 'सैद्धांतिक प्रायिकता',
  'equally likely outcomes': 'समप्रायिक परिणाम',
  'the number sets N, Z, Q and R': 'संख्या समुच्चय N, Z, Q और R',
  'Cartesian products and set notation': 'कार्तीय गुणन और समुच्चय संकेतन',
  'input–output rules': 'निवेश–निर्गत नियम',
  'graphing': 'आलेख बनाना',
  'trigonometric ratios and identities': 'त्रिकोणमितीय अनुपात और सर्वसमिकाएँ',
  'arc length for radian measure': 'रेडियन माप के लिए चाप की लंबाई',
  'the quadratic formula and discriminant': 'द्विघाती सूत्र और विविक्तकर',
  'real-number operations': 'वास्तविक संख्याओं पर संक्रियाएँ',
  'lines in two variables': 'दो चरों वाली रेखाएँ',
  'products and the multiplication principle': 'गुणनफल और गुणन का सिद्धांत',
  'factoring and regrouping products': 'गुणनफलों का गुणनखंड और पुनर्समूहन',
  'nCr values': 'nCr के मान',
  'expanding (a + b)ⁿ for small n': 'छोटे n के लिए (a + b)ⁿ का प्रसार',
  'laws of exponents': 'घातांक के नियम',
  'nth term and sum of an AP': 'समांतर श्रेढ़ी का n-वाँ पद और योग',
  'common ratio of a GP': 'गुणोत्तर श्रेढ़ी का सार्व अनुपात',
  'powers': 'घातें',
  'distance and section formulae': 'दूरी और विभाजन सूत्र',
  'linear equations in two variables': 'दो चरों वाले रैखिक समीकरण',
  'slope': 'ढाल',
  'line equations and distances': 'रेखा के समीकरण और दूरियाँ',
  'completing the square': 'पूर्ण वर्ग बनाना',
  'distance and section formulae in two dimensions': 'दो विमाओं में दूरी और विभाजन सूत्र',
  'factorising to cancel a 0/0 form': '0/0 रूप हटाने के लिए गुणनखंडन',
  'function notation': 'फलन संकेतन',
  'evaluating polynomials': 'बहुपदों का मान निकालना',
  'standard trigonometric limits': 'मानक त्रिकोणमितीय सीमाएँ',
  'grouped mean and median': 'वर्गीकृत आँकड़ों का माध्य और माध्यक',
  'square roots for the standard deviation': 'मानक विचलन के लिए वर्गमूल',
  'events as sets: union and intersection': 'समुच्चय के रूप में घटनाएँ: सम्मिलन और सर्वनिष्ठ',
  'classical probability': 'शास्त्रीय प्रायिकता',
  'counting outcomes': 'परिणामों की गिनती',
  'domain, range and function rules': 'प्रांत, परिसर और फलन के नियम',
  'set notation': 'समुच्चय संकेतन',
  'trigonometric values and periodicity': 'त्रिकोणमितीय मान और आवर्तिता',
  'inverse functions': 'प्रतिलोम फलन',
  'systems of linear equations': 'रैखिक समीकरण निकाय',
  'signed multiplication': 'चिह्न सहित गुणा',
  'matrix operations': 'आव्यूह संक्रियाएँ',
  'limits and derivatives': 'सीमा और अवकलज',
  'trigonometric functions': 'त्रिकोणमितीय फलन',
  'derivatives of inverse trigonometric functions': 'प्रतिलोम त्रिकोणमितीय फलनों के अवकलज',
  'differentiation rules': 'अवकलन के नियम',
  'solving f′(x) = 0': 'f′(x) = 0 हल करना',
  'derivatives to reverse': 'उलटने के लिए अवकलज',
  'algebraic manipulation': 'बीजीय परिवर्तन',
  'integrating trigonometric functions': 'त्रिकोणमितीय फलनों का समाकलन',
  'definite integrals': 'निश्चित समाकल',
  'curve shapes': 'वक्रों के आकार',
  'integration techniques': 'समाकलन की विधियाँ',
  'coordinates in three dimensions': 'त्रिविमीय निर्देशांक',
  'cosine of an angle': 'कोण की कोज्या',
  'dot and cross products': 'अदिश और सदिश गुणनफल',
  'equations of lines': 'रेखाओं के समीकरण',
  'feasible regions': 'सुसंगत क्षेत्र',
  'intersections of lines': 'रेखाओं के प्रतिच्छेद',
  'compound events': 'संयुक्त घटनाएँ',
  'nCr for the binomial distribution': 'द्विपद बंटन के लिए nCr'
});
