# Trains model C — a 32px render with an aspect FLOOR (minAspect 0.25) so
# tall-thin glyphs get real horizontal resolution instead of a 1px smear —
# and merges it into the existing ensemble file as a third voter.
import json, base64, time
import numpy as np, torch, torch.nn as nn, torch.nn.functional as F
torch.manual_seed(23); np.random.seed(23); torch.set_num_threads(10)
SP='/tmp'
D=f'{SP}/inktrainC'; BASE=f'{SP}/train/model-data.new.js'; OUT=f'{SP}/train/model-data.abc.js'
man=json.load(open(f'{D}/manifest.json')); C=len(man['classes'])
def load(name,size,n):
    x=np.frombuffer(open(f'{D}/{name}{size}.img','rb').read(),dtype=np.uint8).reshape(n,1,size,size).astype(np.float32)/255.0
    return torch.from_numpy(x)
yt=torch.from_numpy(np.frombuffer(open(f'{D}/train.lbl','rb').read(),dtype=np.uint8).astype(np.int64))
yv=torch.from_numpy(np.frombuffer(open(f'{D}/val.lbl','rb').read(),dtype=np.uint8).astype(np.int64))
class NetC(nn.Module):
    def __init__(s):
        super().__init__()
        s.c1=nn.Conv2d(1,20,3,padding=1); s.c2=nn.Conv2d(20,40,3,padding=1); s.c3=nn.Conv2d(40,64,3,padding=1)
        s.f1=nn.Linear(64*4*4,192); s.f2=nn.Linear(192,C)
    def forward(s,x):
        x=F.max_pool2d(F.relu(s.c1(x)),2); x=F.max_pool2d(F.relu(s.c2(x)),2); x=F.max_pool2d(F.relu(s.c3(x)),2)
        x=x.flatten(1); x=F.relu(s.f1(x)); x=F.dropout(x,0.2,s.training); return s.f2(x)
def cutout(xb):
    n,_,H,W=xb.shape; k=int(n*0.3)
    if k==0: return xb
    idx=torch.randperm(n)[:k]; xb=xb.clone()
    for i in idx.tolist():
        sz=np.random.randint(4,7); y0=np.random.randint(0,H-sz); x0=np.random.randint(0,W-sz)
        xb[i,:,y0:y0+sz,x0:x0+sz]=0
    return xb
xt=load('train',32,man['train']); xv=load('val',32,man['val'])
net=NetC(); opt=torch.optim.Adam(net.parameters(),lr=1.2e-3)
sched=torch.optim.lr_scheduler.CosineAnnealingLR(opt,T_max=14); BS=256
def ev():
    net.eval(); c=0
    with torch.no_grad():
        for i in range(0,len(xv),1024): c+=(net(xv[i:i+1024]).argmax(1)==yv[i:i+1024]).sum().item()
    net.train(); return c/len(xv)
t0=time.time()
for e in range(14):
    perm=torch.randperm(len(xt)); tot=cor=0; ls=0.0
    for i in range(0,len(xt),BS):
        idx=perm[i:i+BS]; xb,yb=cutout(xt[idx]),yt[idx]
        out=net(xb); loss=F.cross_entropy(out,yb,label_smoothing=0.05)
        opt.zero_grad(); loss.backward(); opt.step()
        ls+=loss.item()*len(idx); tot+=len(idx); cor+=(out.argmax(1)==yb).sum().item()
    sched.step()
    print(f'[C32f] epoch {e+1}/14: loss {ls/tot:.4f} train {100*cor/tot:.2f}% val {100*ev():.2f}% ({time.time()-t0:.0f}s)',flush=True)
accC=ev(); print(f'[C32f] FINAL VAL ACC {100*accC:.2f}%')
def q(t):
    a=t.detach().numpy().astype(np.float32); s=float(np.max(np.abs(a))/127.0) or 1e-8
    return {'shape':list(a.shape),'scale':s,'b64':base64.b64encode(np.clip(np.round(a/s),-127,127).astype(np.int8).tobytes()).decode()}
def fb(t):
    a=t.detach().numpy().astype(np.float32)
    return {'shape':list(a.shape),'b64':base64.b64encode(a.tobytes()).decode()}
src=open(BASE).read(); model=json.loads(src[src.index('export default ')+len('export default '):].rstrip().rstrip(';'))
model['models'].append({'img':32,'minAspect':0.25,'val_acc':round(accC,4),
    'c1w':q(net.c1.weight),'c1b':fb(net.c1.bias),'c2w':q(net.c2.weight),'c2b':fb(net.c2.bias),
    'c3w':q(net.c3.weight),'c3b':fb(net.c3.bias),'f1w':q(net.f1.weight),'f1b':fb(net.f1.bias),
    'f2w':q(net.f2.weight),'f2b':fb(net.f2.bias)})
js=('// Generated by tools/ink-train — int8-quantised v7 ink ensemble (3 voters).\n'
    f'// A28 + B32 aspect-preserved, C32 aspect-floored (minAspect 0.25) {100*accC:.2f}%.\n'
    'export default '+json.dumps(model)+';\n')
open(OUT,'w').write(js); print('wrote',OUT,f'{len(js)/1024:.0f} KB')
