# ─────────────────────────────────────────────────────────────────────────────
# Geometry re-ranker.
#
# The CNN sees a 28²/32² deskewed render. For tall-thin glyphs that render gives
# ~1.3px of horizontal resolution against a ~2.5px brush, so which side a stroke
# bows to — the ONLY thing separating 1 l ( ) / — is quantised away before the
# net ever sees it. This model learns a correction to the ensemble's opinion
# from the geometry measured on the raw strokes.
#
#   logit[c] = alpha * log(cnnP[c] + eps) + W[c]·geom + b[c]
#
# Deliberately linear and tiny: 37×56 + 56 ≈ 2.1k floats. It must not be able to
# overrule a confident CNN wholesale — only to tip decisions the render cannot
# make. Exported as float32 base64 for the on-device forward pass.
# ─────────────────────────────────────────────────────────────────────────────
import json, base64
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(11); np.random.seed(11)
D = '/tmp/rerank'
OUT_JS = '../../client/src/ink/rerank-data.js'

man = json.load(open(f'{D}/manifest.json'))
n, C, Fn = man['n'], man['nClasses'], man['nFeatures']

P = np.fromfile(f'{D}/probs.f32', dtype=np.float32).reshape(n, C)
X = np.fromfile(f'{D}/feats.f32', dtype=np.float32).reshape(n, Fn)
y = np.fromfile(f'{D}/labels.u8', dtype=np.uint8).astype(np.int64)

# split by index parity within each class so both sets cover every class
idx = np.arange(n)
rs = np.random.RandomState(3); rs.shuffle(idx)
cut = int(n * 0.85)
tr, va = idx[:cut], idx[cut:]

P_t = torch.from_numpy(np.log(P + 1e-4))
X_t = torch.from_numpy(X)
y_t = torch.from_numpy(y)

base_val = (P[va].argmax(1) == y[va]).mean()
print(f'samples {n}  classes {C}  features {Fn}')
print(f'CNN alone, val: {100*base_val:.2f}%')


class ReRank(nn.Module):
    def __init__(self):
        super().__init__()
        self.alpha = nn.Parameter(torch.tensor(1.0))
        self.lin = nn.Linear(Fn, C)
        nn.init.zeros_(self.lin.weight)   # start as a no-op on top of the CNN
        nn.init.zeros_(self.lin.bias)

    def forward(self, logp, x):
        return self.alpha * logp + self.lin(x)


net = ReRank()
opt = torch.optim.Adam(net.parameters(), lr=6e-3)
sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=60)
BS = 1024
best, best_state = 0.0, None

for epoch in range(60):
    perm = torch.randperm(len(tr))
    net.train()
    for i in range(0, len(tr), BS):
        b = torch.from_numpy(tr[perm[i:i + BS].numpy()])
        loss = F.cross_entropy(net(P_t[b], X_t[b]), y_t[b], label_smoothing=0.03)
        # keep the correction small: it is a nudge, not a second opinion
        loss = loss + 3e-4 * net.lin.weight.abs().mean()
        opt.zero_grad(); loss.backward(); opt.step()
    sched.step()
    net.eval()
    with torch.no_grad():
        vb = torch.from_numpy(va)
        acc = (net(P_t[vb], X_t[vb]).argmax(1) == y_t[vb]).float().mean().item()
    if acc > best:
        best = acc
        best_state = {k: v.detach().clone() for k, v in net.state_dict().items()}
    if (epoch + 1) % 10 == 0:
        print(f'epoch {epoch+1}/60  val {100*acc:.2f}%  (best {100*best:.2f}%)  alpha {net.alpha.item():.3f}')

net.load_state_dict(best_state)
print(f'\nre-ranked val: {100*best:.2f}%   (CNN alone {100*base_val:.2f}%)  delta {100*(best-base_val):+.2f} pts')

# where did it help? per-class deltas, worst-first
net.eval()
with torch.no_grad():
    vb = torch.from_numpy(va)
    pred_new = net(P_t[vb], X_t[vb]).argmax(1).numpy()
pred_old = P[va].argmax(1)
truth = y[va]
classes = man['classes']
rows = []
for c in range(C):
    m = truth == c
    if m.sum() < 5: continue
    rows.append((classes[c], (pred_old[m] == c).mean(), (pred_new[m] == c).mean(), int(m.sum())))
rows.sort(key=lambda r: (r[2] - r[1]))
print('\nlargest per-class changes (class, CNN, re-ranked, n):')
for r in rows[:6]:  print(f'  {r[0]:>6}  {100*r[1]:5.1f}% -> {100*r[2]:5.1f}%   n={r[3]}')
print('  ...')
for r in rows[-8:]: print(f'  {r[0]:>6}  {100*r[1]:5.1f}% -> {100*r[2]:5.1f}%   n={r[3]}')

W = net.lin.weight.detach().numpy().astype(np.float32)   # (C, Fn)
b = net.lin.bias.detach().numpy().astype(np.float32)     # (C,)
alpha = float(net.alpha.item())

js = (
    '// Generated by tools/ink-train/train_rerank.py — geometry re-ranker.\n'
    f'// Linear correction on the CNN ensemble from {Fn} geometric features the\n'
    f'// rasteriser discards. val {100*best:.2f}% vs {100*base_val:.2f}% for the ensemble alone\n'
    f'// ({100*(best-base_val):+.2f} pts) on {len(va)} held-out synthetic glyphs.\n'
    'export default ' + json.dumps({
        'alpha': alpha,
        'nFeatures': Fn,
        'classes': man['classes'],
        'w': {'shape': [C, Fn], 'b64': base64.b64encode(W.tobytes()).decode()},
        'b': {'shape': [C], 'b64': base64.b64encode(b.tobytes()).decode()},
        'val_acc': round(best, 4),
        'cnn_only_acc': round(float(base_val), 4),
    }) + ';\n'
)
open(OUT_JS, 'w').write(js)
print(f'\nwrote {OUT_JS}  {len(js)/1024:.1f} KB')
