import { sqliteHandle } from './store.js';
import { BILLING_SCHEMA_VERSION } from './schemaVersions.js';

export { BILLING_SCHEMA_VERSION };

function addColumnIfMissing(db, table, column, ddl) {
  const columns = new Set(db.pragma(`table_info('${table}')`).map(row => row.name));
  if (columns.has(column)) return false;
  db.exec(`ALTER TABLE ${table} ADD COLUMN ${ddl}`);
  return true;
}

/**
 * Billing is an optional deployment subsystem, so its schema is versioned
 * independently from the core account/sync database. The migration is
 * idempotent and runs before any provider adapter is constructed.
 */
export function ensureBillingSchema(db) {
  // Postgres: supabase/migrations owns the billing tables and seeds
  // billing_schema_version; this process never creates tables there.
  db = sqliteHandle(db);
  if (!db) return BILLING_SCHEMA_VERSION;
  db.exec(`
    CREATE TABLE IF NOT EXISTS billing_subscriptions (
      provider TEXT NOT NULL CHECK(provider IN ('apple','google','web')),
      provider_subscription_id TEXT NOT NULL,
      account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
      product_id TEXT NOT NULL,
      cadence TEXT CHECK(cadence IN ('monthly','annual') OR cadence IS NULL),
      trial_claimed INTEGER NOT NULL DEFAULT 0 CHECK(trial_claimed IN (0,1)),
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      last_effective_at INTEGER NOT NULL DEFAULT 0,
      last_event_rank INTEGER NOT NULL DEFAULT 0,
      last_event_id TEXT,
      PRIMARY KEY(provider, provider_subscription_id)
    );
    CREATE INDEX IF NOT EXISTS idx_billing_subscriptions_account
      ON billing_subscriptions(account_id, provider, created_at);

    -- One row is the server-side authority for introductory trial eligibility.
    -- A provider request with an ambiguous outcome keeps its reservation: it is
    -- safer to require support to release one trial than to manufacture two.
    CREATE TABLE IF NOT EXISTS billing_trial_claims (
      account_id TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
      provider TEXT NOT NULL CHECK(provider IN ('apple','google','web')),
      provider_subscription_id TEXT NOT NULL,
      claimed_at INTEGER NOT NULL
    );

    -- StoreKit's appAccountToken is the stable, opaque join between a Pri cloud
    -- account and an App Store transaction. It is generated by the server and
    -- never derived from an email/name, so a signed transaction can be matched
    -- without putting Pri account identifiers into App Store metadata.
    CREATE TABLE IF NOT EXISTS billing_apple_accounts (
      account_id TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
      app_account_token TEXT NOT NULL UNIQUE,
      created_at INTEGER NOT NULL
    );
  `);

  // WP server-commerce-classes: billing schema v3 — cancellation state and the
  // payment/refund ledger that lets refund webhooks be mapped back to a
  // subscription and account (cloud-03, cloud-11, commercial-14).
  addColumnIfMissing(db, 'billing_subscriptions', 'cancel_requested_at', 'cancel_requested_at INTEGER');
  addColumnIfMissing(db, 'billing_subscriptions', 'cancel_mode',
    "cancel_mode TEXT CHECK(cancel_mode IN ('cycle-end','immediate') OR cancel_mode IS NULL)");
  addColumnIfMissing(db, 'billing_subscriptions', 'cancel_reason', 'cancel_reason TEXT');
  db.exec(`
    -- Provider payments observed through verified webhooks. Amounts are the
    -- provider's minor units (paise). Only ids, amounts and timestamps are kept;
    -- no card, UPI or customer details ever reach this table.
    CREATE TABLE IF NOT EXISTS billing_payments (
      provider TEXT NOT NULL CHECK(provider IN ('apple','google','web')),
      payment_id TEXT NOT NULL,
      provider_subscription_id TEXT NOT NULL,
      account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
      amount INTEGER NOT NULL DEFAULT 0,
      currency TEXT,
      status TEXT,
      captured_at INTEGER NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      PRIMARY KEY(provider, payment_id)
    );
    CREATE INDEX IF NOT EXISTS idx_billing_payments_subscription
      ON billing_payments(provider, provider_subscription_id, captured_at);

    CREATE TABLE IF NOT EXISTS billing_refunds (
      provider TEXT NOT NULL CHECK(provider IN ('apple','google','web')),
      refund_id TEXT NOT NULL,
      payment_id TEXT NOT NULL,
      amount INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL CHECK(status IN ('pending','processed','failed')),
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      PRIMARY KEY(provider, refund_id)
    );
    CREATE INDEX IF NOT EXISTS idx_billing_refunds_payment ON billing_refunds(provider, payment_id);
  `);

  // Billing schema v4 (§19 StoreKit entitlement state machine). Each provider
  // subscription carries its own last-applied lifecycle so the account
  // entitlement is derived from every subscription the account holds — an
  // event for one subscription can no longer overwrite Premium that another,
  // still-paid subscription (or a support grant) provides. The Apple signed
  // data the server verified is kept verbatim so an operator can recompute
  // the entitlement from Apple's own signatures and report drift
  // (server/tools/billing-reconcile.mjs, docs/operations/billing-reconciliation.md).
  addColumnIfMissing(db, 'billing_subscriptions', 'state_plan',
    "state_plan TEXT CHECK(state_plan IN ('free','premium') OR state_plan IS NULL)");
  addColumnIfMissing(db, 'billing_subscriptions', 'state_status', 'state_status TEXT');
  addColumnIfMissing(db, 'billing_subscriptions', 'state_period_end', 'state_period_end INTEGER');
  addColumnIfMissing(db, 'billing_subscriptions', 'state_grace_until', 'state_grace_until INTEGER');
  db.exec(`
    -- Apple-signed JWS the server verified: device transactions (purchase,
    -- restore, Transaction.updates) and App Store Server Notifications v2.
    -- account_id is NULL for a notification that names no Pri account (no or
    -- an unknown appAccountToken): it is acknowledged and kept for an operator
    -- rather than refused into Apple's retry loop.
    CREATE TABLE IF NOT EXISTS billing_apple_signed_events (
      event_id TEXT PRIMARY KEY,
      kind TEXT NOT NULL CHECK(kind IN ('transaction','notification')),
      account_id TEXT REFERENCES accounts(id) ON DELETE CASCADE,
      original_transaction_id TEXT NOT NULL,
      transaction_id TEXT NOT NULL,
      notification_type TEXT,
      environment TEXT NOT NULL,
      signed_date INTEGER NOT NULL,
      signed_payload TEXT NOT NULL,
      received_at INTEGER NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_billing_apple_signed_events_subscription
      ON billing_apple_signed_events(original_transaction_id, signed_date);
    CREATE INDEX IF NOT EXISTS idx_billing_apple_signed_events_account
      ON billing_apple_signed_events(account_id, signed_date);
  `);

  db.prepare("INSERT OR REPLACE INTO platform_meta(key,value) VALUES ('billing_schema_version',?)").run(String(BILLING_SCHEMA_VERSION));
  return BILLING_SCHEMA_VERSION;
}
