// ─────────────────────────────────────────────────────────────────────────────
// Pri Learning · /v1/tutor
//
// Grounded, three-level help for a practice question: a nudge, then a Socratic
// question, then a narrated walkthrough of the verified solution — and, once
// the ladder has started, a conversation: the student types a question in
// their own words and the tutor answers under the same rules. The words may
// come from a model; the mathematics never does, and nothing here marks.
//
// What this route guarantees, in the order the handler enforces it:
//
//   1. Signed in, email verified, guardian consent (mounted in router.js), and
//      a per-account hourly limit.
//   2. Practice only. A body that does not say `context: "practice"` is
//      refused, and one that says "exam" is refused with TUTOR_EXAM_LOCKED.
//      The local backend refuses earlier still (assertPracticeRow), so an exam
//      question never reaches this server; this is the second wall, not the
//      only one.
//   3. A closed, size-bounded body. No names, emails or profile ids: the only
//      student data sent on is the work lines and typed answer.
//   4. Cache before spend. An identical request in the last 24 hours is
//      answered from tutor_cache without a model call.
//   5. One unit of the deployment-wide paid-call ceiling per model call.
//   6. A per-account daily allowance (PRI_TUTOR_CALLS_PER_ACCOUNT_DAY, higher
//      for premium via PRI_TUTOR_CALLS_PER_ACCOUNT_DAY_PREMIUM), so one account
//      cannot drain the shared ceiling, and maths-only content limits, so the
//      route cannot be used as a general model proxy.
//   7. The reply is checked against the verified solution (tutorGuard.js). A
//      leaked answer is regenerated once; a second leak falls back to the
//      question's own authored hint, or a generic deterministic nudge. Captions
//      may only reword: their maths must be verbatim spans of the verified step.
//
//   8. A conversational turn (level "ask") carries the student's typed question
//      (≤600 chars, control characters stripped, framed to the model as data)
//      and the last six turns of the exchange, trimmed here whatever the client
//      sent. Its cache key is scoped to the account: a free-text exchange is
//      never read back by another account. The fixed-ladder levels keep the
//      content-keyed shared cache, because their requests carry no free text.
//   9. POST /stream answers an ask/nudge/socratic turn as server-sent events.
//      Every refusal above still happens first, as JSON, before a byte of the
//      stream; the model's text is released one guarded sentence at a time
//      (tutorGuard.createReleaseGate), a leak ends the stream with the authored
//      hint (`event: fallback`) and is never cached, and one session may hold
//      one open stream — a newer one closes the older.
//
// What it cannot see: whether the question is in an active exam. The client
// tells it (`context`), and the local backend refuses exam rows before calling;
// a modified client could misreport. The daily allowance bounds that misuse,
// and the replies never contain the answer whatever the context.
//
// Two groundings. A SERVER-ISSUED practice question (/v1/practice/issue) is
// grounded here, from the server's own escrowed question: the body names it
// (`serverQuestionId`) and carries no prompt, step or answer — the device does
// not hold them and its word for them would not be taken. The escrow is read
// for the signed-in account only, so another account's question id is a 404,
// and until that question is resolved the guard never excuses the answer, the
// walkthrough level is refused, and no reply field carries the solution.
//
// A DEVICE question (generated by the bundled engine, no server id) keeps the
// older contract, where the server cannot verify the solution it is grounded
// in: the "verified" steps and answer are the client's word. What bounds that: the body is
// closed and size-limited, the guard protects the client's own stated answer
// and step results so a forged solution cannot extract a real one, a reply
// may never echo a step verbatim, and the cache key covers the solution's
// content so one client's forgery is never served to another.
// ─────────────────────────────────────────────────────────────────────────────
import { createHash } from 'node:crypto';
import { publicEntitlement } from './entitlements.js';
import { asyncRouter } from './asyncRouter.js';
import { asStore, sqliteHandle } from './store.js';
import { consumeRateLimit, rateLimit, requireSession, requireVerifiedEmail, sha256 } from './security.js';
import { consumePaidCall, refusePaidCall } from './spendCeiling.js';
import { issuedQuestionForTutor } from './practice.js';
import { buildGuard, captionWordingOk, createReleaseGate, leakedExpressions, solutionSpans } from './tutorGuard.js';
import {
  MAX_CAPTION_CHARS, MAX_HISTORY_TURNS, MAX_STREAM_CHARS, MAX_TURN_CHARS, TUTOR_LEVELS, TUTOR_LOCALES, TUTOR_REQUEST_LEVELS,
  TUTOR_TURN_LEVEL, TutorProviderError, askTutorModel, providerConfig, streamTutorModel
} from './tutorProvider.js';

export const TUTOR_CACHE_TTL_MS = 24 * 60 * 60 * 1000;
export const MAX_TUTOR_BODY_BYTES = 48 * 1024;
export const TUTOR_RATE_LIMIT = Object.freeze({ limit: 60, windowMs: 60 * 60 * 1000 });
export const TUTOR_STREAM_RATE_LIMIT = Object.freeze({ limit: 60, windowMs: 60 * 60 * 1000 });
/** The levels /stream serves: text replies. Walkthrough captions are structured and stay on /help. */
export const TUTOR_STREAM_LEVELS = Object.freeze(['nudge', 'socratic', TUTOR_TURN_LEVEL]);

// C0 and C1 control characters and DEL, which a model should never see and a
// terminal should never be handed; tab and newline are kept as whitespace.
const CONTROL = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/g;
const cleanTurn = value => String(value ?? '').replace(CONTROL, '').replace(/\s+/g, ' ').trim();

const LIMITS = Object.freeze({
  prompt: 2_000, steps: 24, stepHeading: 300, stepDetail: 700, solution: 8_000, answer: 300,
  hints: 6, hint: 500, lines: 40, line: 400, work: 4_000, typed: 300, captions: 24, caption: 700
});
export const TUTOR_DAILY_DEFAULTS = Object.freeze({ free: 40, premium: 120 });

// A maths token: a digit, an operator, a relation, a $…$ span or a KaTeX
// command. The tutor is for mathematics; text with none of these is not a
// question it should be asked about, and refusing it keeps the route from
// being a general-purpose model proxy.
const MATHS = /[0-9०-९=+\-−×÷*/^<>≤≥√π$∫∑%]|\\[a-z]+/i;
const hasMaths = value => MATHS.test(String(value ?? ''));
const notMaths = message => invalid(message, 'TUTOR_NOT_MATHS');

/** Generic deterministic help, for a guarded reply on a question with no authored hint. */
export const GENERIC_HELP = Object.freeze({
  en: Object.freeze({
    nudge: 'Look again at what the question gives you, and decide which part of it to deal with first.',
    socratic: 'What is the very next thing you could do that keeps both sides balanced, and why?',
    walkthrough: 'Follow the verified solution one step at a time.'
  }),
  hi: Object.freeze({
    nudge: 'प्रश्न में दी गई जानकारी फिर से देखें, और तय करें कि पहले किस हिस्से पर काम करना है।',
    socratic: 'अगला कौन-सा क़दम है जिससे दोनों पक्ष संतुलित रहें, और क्यों?',
    walkthrough: 'जाँचे हुए हल को एक-एक क़दम करके देखें।'
  })
});

function ensureTable(db) {
  // SQLite builds its schema here; Postgres is migrated (supabase/migrations).
  const raw = sqliteHandle(db);
  if (!raw) return;
  raw.exec(`CREATE TABLE IF NOT EXISTS tutor_cache (
    cache_key TEXT PRIMARY KEY,
    response_json TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_tutor_cache_expires ON tutor_cache(expires_at);`);
}

const invalid = (message, code = 'TUTOR_BODY_INVALID', status = 400) => ({ ok: false, status, code, message });
const ISSUED_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Ground a request that names a server-issued question in the server's own
 * escrowed copy of it. Device requests (no serverQuestionId) pass through.
 *
 * Account scoping is the lookup itself: the escrow row is keyed by account, so
 * a question issued to another account, an expired one and one that never
 * existed are the same 404. Nothing the device said about the solution or about
 * which of its lines are verified survives: the solution comes from escrow and
 * the Step Check is re-run here. While the question is unresolved the guard is
 * told no line is verified and no line is the first mistake, so the answer is never excused in a reply — a
 * tutor turn cannot be used to test a guessed answer — and the walkthrough
 * level, whose captions restate the solution, is refused.
 */
export async function groundIssued(db, accountId, request, at = Date.now()) {
  if (!request.serverQuestionId) return { ok: true, request };
  const issued = await issuedQuestionForTutor(db, accountId, request.serverQuestionId, at);
  if (!issued) return invalid('This question does not belong to this account.', 'TUTOR_QUESTION_NOT_FOUND', 404);
  if (request.level === 'walkthrough' && !issued.resolved) {
    return invalid('The walkthrough follows the reveal of a server-issued question.', 'TUTOR_LEVEL_ORDER', 409);
  }
  const checked = validateQuestion({
    prompt: issued.prompt.slice(0, LIMITS.prompt),
    steps: issued.steps.slice(0, LIMITS.steps)
      .map(s => ({ h: s.h.slice(0, LIMITS.stepHeading), d: s.d.slice(0, LIMITS.stepDetail) }))
      .filter(s => s.h || s.d),
    answer: issued.answerText.slice(0, LIMITS.answer),
    hints: issued.hints.slice(0, LIMITS.hints).map(h => h.slice(0, LIMITS.hint))
  }, { authored: true });
  // An issued question the tutor cannot be grounded in (no authored steps, no
  // answer text, too long) is the server's own content gap, not a bad body.
  if (!checked.ok) return invalid('This question has no verified solution the tutor can be grounded in.', 'TUTOR_UNGROUNDED', 422);
  // The Step Check runs in the marker pool (off this thread, under a hard
  // deadline). Its verdict is withheld below until the question is resolved,
  // so it is not run at all before then: nothing is lost, and an unresolved
  // question cannot be used to spend marking time.
  const evidence = issued.resolved
    ? await issued.workEvidence(request.studentWork.lines)
    : { firstBreak: -1, verifiedLines: 0, misconception: null };
  return {
    ok: true,
    request: {
      ...request,
      questionVersion: issued.version.slice(0, 60),
      question: checked.question,
      studentWork: {
        ...request.studentWork,
        // Which line is the first mistake is a verdict on the student's working.
        // Before the question is resolved it would cost nothing and tell them
        // whether a guessed line is right, so it is withheld with the rest.
        firstBreak: issued.resolved ? evidence.firstBreak : -1,
        verifiedLines: issued.resolved ? evidence.verifiedLines : 0,
        misconception: null
      }
    }
  };
}
const isText = (value, max, { required = false } = {}) =>
  (value === undefined && !required) || (typeof value === 'string' && value.length <= max && (!required || value.trim().length > 0));
const closed = (object, allowed) => Object.keys(object).filter(key => !allowed.includes(key));
const plain = value => !!value && typeof value === 'object' && !Array.isArray(value);

/**
 * A question and its verified solution, checked and reduced to what the model
 * may see. Used for a device question's body and, identically, for the
 * material the server reads from its own escrow for an issued question.
 *
 * The maths-only rules exist so a device cannot use the route as a general
 * model proxy by describing an arbitrary "question". They are applied to what
 * a device describes. `authored` — the server's own issued curriculum question
 * — is exempt from them and from nothing else: a worded question about method
 * ("which check is valid?") is still mathematics teaching, and the size bounds
 * and the need for verified steps and an answer hold either way.
 */
function validateQuestion(q, { authored = false } = {}) {
  if (!plain(q)) return invalid('question must describe the question and its verified solution.');
  const qUnknown = closed(q, ['prompt', 'steps', 'answer', 'hints']);
  if (qUnknown.length) return invalid(`Unexpected question field: ${qUnknown.join(', ')}.`);
  if (!isText(q.prompt, LIMITS.prompt, { required: true })) return invalid('question.prompt is required and bounded.');
  if (!Array.isArray(q.steps) || !q.steps.length || q.steps.length > LIMITS.steps) {
    return invalid(`question.steps must hold 1 to ${LIMITS.steps} verified steps — help is only given against a verified solution.`, 'TUTOR_UNGROUNDED');
  }
  for (const step of q.steps) {
    if (!plain(step) || closed(step, ['h', 'd']).length || !isText(step.h, LIMITS.stepHeading) || !isText(step.d, LIMITS.stepDetail)) {
      return invalid('Each step is { h, d } with bounded text.');
    }
  }
  if (!isText(q.answer, LIMITS.answer, { required: true })) return invalid('question.answer is required: the guard checks every reply against it.', 'TUTOR_UNGROUNDED');
  // Maths only: a question, a solution and an answer that carry mathematics.
  if (!authored && !hasMaths(q.prompt)) return notMaths('The tutor helps with mathematics questions only.');
  const solutionChars = q.steps.reduce((n, step) => n + String(step.h || '').length + String(step.d || '').length, 0);
  if (solutionChars > LIMITS.solution) return invalid(`The verified solution is at most ${LIMITS.solution} characters.`, 'TUTOR_REQUEST_TOO_LARGE', 413);
  if (!authored && q.steps.filter(step => hasMaths(step.h) || hasMaths(step.d)).length < Math.ceil(q.steps.length / 2)) {
    return notMaths('A verified solution is mostly mathematics.');
  }
  if (!authored && !hasMaths(q.answer) && q.answer.length > 60) return notMaths('The answer is a mathematical result.');
  if (q.hints !== undefined && (!Array.isArray(q.hints) || q.hints.length > LIMITS.hints || !q.hints.every(h => typeof h === 'string' && h.length <= LIMITS.hint))) {
    return invalid('question.hints must be a short list of authored hints.');
  }
  return {
    ok: true,
    question: {
      prompt: q.prompt.trim(),
      steps: q.steps.map(s => ({ h: String(s.h || '').trim(), d: String(s.d || '').trim() })),
      answer: q.answer.trim(),
      hints: (q.hints || []).map(h => h.trim()).filter(Boolean)
    }
  };
}

/**
 * The whole body, validated and reduced to exactly what the model may see.
 * Returns { ok: true, request } or a refusal with its HTTP status and code.
 */
export function validateTutorRequest(body) {
  if (!plain(body)) return invalid('Send a JSON body describing the question and the help wanted.');

  // Exam context is checked before anything else, so an exam body is refused
  // for being an exam body — never for some other field it happened to carry.
  if (body.context === 'exam' || body.mode === 'exam' || body.examId !== undefined) {
    return invalid('Help is not available during an exam.', 'TUTOR_EXAM_LOCKED', 403);
  }
  const unknown = closed(body, ['context', 'level', 'locale', 'questionId', 'questionVersion', 'question', 'serverQuestionId', 'studentWork', 'captions', 'message', 'history']);
  if (unknown.length) return invalid(`Unexpected field: ${unknown.join(', ')}.`);
  if (body.context !== 'practice') return invalid('The tutor helps with practice questions only; send context "practice".', 'TUTOR_CONTEXT_REQUIRED');
  if (!TUTOR_REQUEST_LEVELS.includes(body.level)) return invalid(`level must be one of ${TUTOR_REQUEST_LEVELS.join(', ')}.`);
  const asking = body.level === TUTOR_TURN_LEVEL;
  if (!asking && (body.message !== undefined || body.history !== undefined)) return invalid('message and history are only sent with level "ask".');
  const locale = body.locale === undefined ? 'en' : body.locale;
  if (!TUTOR_LOCALES.includes(locale)) return invalid(`locale must be one of ${TUTOR_LOCALES.join(', ')}.`);
  // A server-issued question is named, never described: the server grounds the
  // help in its own escrowed copy (groundIssued, below). A body that names one
  // AND supplies a solution is refused outright rather than half-trusted.
  const issued = body.serverQuestionId !== undefined;
  if (issued) {
    if (!(typeof body.serverQuestionId === 'string' && ISSUED_ID.test(body.serverQuestionId))) return invalid('serverQuestionId is the id of a question this server issued.');
    if (body.question !== undefined) return invalid('A server-issued question is grounded by the server; do not send question with serverQuestionId.');
    if (body.questionId !== undefined && body.questionId !== body.serverQuestionId) return invalid('questionId, when sent with serverQuestionId, must be the same id.');
  } else if (!(typeof body.questionId === 'string' && /^[A-Za-z0-9._:-]{1,120}$/.test(body.questionId))) return invalid('questionId is required and is an opaque id.');
  if (!isText(body.questionVersion, 60)) return invalid('questionVersion must be a short string.');

  let question = null;
  if (!issued) {
    const checkedQuestion = validateQuestion(body.question);
    if (!checkedQuestion.ok) return checkedQuestion;
    question = checkedQuestion.question;
  }

  const work = body.studentWork === undefined ? {} : body.studentWork;
  if (!plain(work)) return invalid('studentWork must be an object.');
  const wUnknown = closed(work, ['lines', 'typedAnswer', 'firstBreak', 'verifiedLines', 'misconception']);
  if (wUnknown.length) return invalid(`Unexpected studentWork field: ${wUnknown.join(', ')}.`);
  if (work.lines !== undefined && (!Array.isArray(work.lines) || work.lines.length > LIMITS.lines || !work.lines.every(l => typeof l === 'string' && l.length <= LIMITS.line))) {
    return invalid(`studentWork.lines must be at most ${LIMITS.lines} lines of at most ${LIMITS.line} characters.`);
  }
  if ((work.lines || []).reduce((n, l) => n + l.length, 0) > LIMITS.work) {
    return invalid(`studentWork is at most ${LIMITS.work} characters.`, 'TUTOR_REQUEST_TOO_LARGE', 413);
  }
  if ((work.lines || []).some(l => l.length > 80 && !hasMaths(l))) return notMaths('Working lines are mathematics.');
  if (!isText(work.typedAnswer, LIMITS.typed)) return invalid('studentWork.typedAnswer is bounded.');
  if (work.typedAnswer && work.typedAnswer.length > 60 && !hasMaths(work.typedAnswer)) return notMaths('An answer is mathematics.');
  if (work.verifiedLines !== undefined && (!Number.isInteger(work.verifiedLines) || work.verifiedLines < 0 || work.verifiedLines > LIMITS.lines)) {
    return invalid('studentWork.verifiedLines counts the lines the deterministic checker verified.');
  }
  if (work.firstBreak !== undefined && (!Number.isInteger(work.firstBreak) || work.firstBreak < -1 || work.firstBreak >= LIMITS.lines)) {
    return invalid('studentWork.firstBreak must be a line index or -1.');
  }
  if (work.misconception !== undefined && !(typeof work.misconception === 'string' && /^[a-z0-9._:-]{1,80}$/i.test(work.misconception))) {
    return invalid('studentWork.misconception must be a stable misconception id, not free text.');
  }

  let captions = [];
  if (body.level === 'walkthrough') {
    if (!Array.isArray(body.captions) || !body.captions.length || body.captions.length > LIMITS.captions) {
      return invalid(`A walkthrough sends 1 to ${LIMITS.captions} deterministic captions to rephrase.`);
    }
    for (const c of body.captions) {
      if (!plain(c) || closed(c, ['id', 'text']).length || !(typeof c.id === 'string' && /^[a-z0-9_-]{1,40}$/i.test(c.id)) || !isText(c.text, LIMITS.caption, { required: true })) {
        return invalid('Each caption is { id, text }.');
      }
    }
    captions = body.captions.map(c => ({ id: c.id, text: c.text.trim() }));
  } else if (body.captions !== undefined) {
    return invalid('captions are only sent with the walkthrough level.');
  }

  // The conversational turn: the student's question, bounded and cleaned, and
  // the recent exchange, trimmed to the last MAX_HISTORY_TURNS turns here.
  let message = '';
  let history = [];
  if (asking) {
    if (typeof body.message !== 'string' || body.message.length > MAX_TURN_CHARS * 2) return invalid(`message is the student's question, at most ${MAX_TURN_CHARS} characters.`);
    message = cleanTurn(body.message);
    if (!message) return invalid('message must say something.');
    if (message.length > MAX_TURN_CHARS) return invalid(`message is at most ${MAX_TURN_CHARS} characters.`, 'TUTOR_REQUEST_TOO_LARGE', 413);
    if (body.history !== undefined) {
      if (!Array.isArray(body.history) || body.history.length > MAX_HISTORY_TURNS * 4) return invalid('history is a short list of earlier turns.');
      for (const turn of body.history) {
        if (!plain(turn) || closed(turn, ['role', 'text']).length || !['student', 'tutor'].includes(turn.role) || typeof turn.text !== 'string' || turn.text.length > MAX_TURN_CHARS * 2) {
          return invalid('Each history turn is { role: "student" | "tutor", text }.');
        }
      }
      history = body.history
        .map(turn => ({ role: turn.role, text: cleanTurn(turn.text).slice(0, MAX_TURN_CHARS) }))
        .filter(turn => turn.text)
        .slice(-MAX_HISTORY_TURNS);
    }
  }

  const lines = (work.lines || []).map(l => l.trim()).filter(Boolean);
  return {
    ok: true,
    request: {
      level: body.level,
      ...(asking ? { message, history } : {}),
      locale,
      questionId: issued ? body.serverQuestionId : body.questionId,
      questionVersion: body.questionVersion || '1',
      // null for a server-issued question until groundIssued() fills it from escrow.
      question,
      ...(issued ? { serverQuestionId: body.serverQuestionId } : {}),
      studentWork: {
        lines,
        typedAnswer: work.typedAnswer ? work.typedAnswer.trim() : '',
        firstBreak: Number.isInteger(work.firstBreak) ? work.firstBreak : -1,
        verifiedLines: Number.isInteger(work.verifiedLines) ? Math.min(work.verifiedLines, lines.length) : 0,
        misconception: work.misconception || null
      },
      captions
    }
  };
}

/**
 * Identical help asks hash to one key: question id + version + content, work,
 * level, locale. A ladder level's key is content only, so identical requests
 * from different accounts share one reply. A conversational turn's key also
 * takes `scope` — a hash of the account, never the id itself — so free text a
 * student typed is cached for that account alone.
 */
export function tutorCacheKey(request, scope = null) {
  const asking = request.level === TUTOR_TURN_LEVEL;
  if (asking && !scope) throw new Error('a conversational turn is cached per account: scope is required');
  const material = JSON.stringify([
    'pri-tutor-v1', request.level, request.locale, request.questionId, request.questionVersion,
    request.question.prompt, request.question.steps, request.question.answer, request.question.hints,
    request.studentWork.lines, request.studentWork.typedAnswer, request.studentWork.firstBreak,
    request.studentWork.verifiedLines, request.studentWork.misconception, request.captions,
    ...(asking ? [scope, request.message, request.history] : [])
  ]);
  return createHash('sha256').update(material).digest('hex');
}

/** The per-account cache scope: a truncated hash, so the cache table never holds an account id. */
export const cacheScope = accountId => sha256(`tutor-scope:${accountId}`).slice(0, 24);

/** The authored, deterministic hint for this level, or the generic one when the question has none. */
export function deterministicHelp(request) {
  const hints = request.question.hints;
  if (request.level === TUTOR_TURN_LEVEL) {
    // A conversation walks the authored hints one turn at a time, then holds
    // on the last; with none written, a Socratic question.
    const turn = (request.history || []).filter(t => t.role === 'tutor').length;
    if (hints.length) return hints[Math.min(turn, hints.length - 1)];
    return (GENERIC_HELP[request.locale] || GENERIC_HELP.en).socratic;
  }
  if (hints.length) return hints[Math.min(TUTOR_LEVELS.indexOf(request.level), hints.length - 1)];
  return (GENERIC_HELP[request.locale] || GENERIC_HELP.en)[request.level];
}

const positiveInt = value => { const n = Number(value); return Number.isInteger(n) && n > 0 ? n : null; };

/**
 * How many tutor requests this account may send to the model in a day. The
 * plan is read from the server's own entitlement snapshot; a premium plan
 * ('additional-ai-usage') gets the larger allowance.
 */
export async function tutorDailyLimit(db, accountId, env = process.env) {
  const row = await db.get('SELECT * FROM entitlement_snapshots WHERE account_id = ?', [accountId]);
  const plan = row ? publicEntitlement(row).plan : 'free';
  return plan === 'premium'
    ? positiveInt(env.PRI_TUTOR_CALLS_PER_ACCOUNT_DAY_PREMIUM) || TUTOR_DAILY_DEFAULTS.premium
    : positiveInt(env.PRI_TUTOR_CALLS_PER_ACCOUNT_DAY) || TUTOR_DAILY_DEFAULTS.free;
}

/** The tutor ships dark: the route exists only where PRI_FEATURE_TUTOR=1. */
export function tutorFeatureEnabled(env = process.env) {
  return String(env.PRI_FEATURE_TUTOR || '').trim() === '1';
}

export function createTutorRouter(db, {
  ask = askTutorModel,
  stream = streamTutorModel,
  env = process.env,
  now = () => Date.now()
} = {}) {
  db = asStore(db);
  ensureTable(db);
  const router = asyncRouter();
  // One open stream per session (account_sessions.id → its abort controller).
  // A second stream from the same session closes the first before it starts.
  const openStreams = new Map();

  // Off: every tutor path is the platform's ordinary 404, before any session
  // lookup, so a dark deployment does not even reveal that the route exists.
  router.use((req, res, next) => {
    if (tutorFeatureEnabled(env)) return next();
    res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Platform endpoint not found.' } });
  });

  router.get('/status', requireSession(db), async (req, res) => {
    const config = providerConfig(env);
    res.json({ available: config.configured, model: config.configured ? config.model : null, levels: TUTOR_LEVELS, conversation: true, streaming: true });
  });

  async function cached(key, at) {
    const row = await db.get('SELECT response_json, expires_at FROM tutor_cache WHERE cache_key = ?', [key]);
    if (!row) return null;
    if (Number(row.expires_at) <= at) {
      await db.run('DELETE FROM tutor_cache WHERE cache_key = ?', [key]);
      return null;
    }
    try { return JSON.parse(row.response_json); } catch { return null; }
  }

  async function remember(key, value, at) {
    await db.run(`INSERT INTO tutor_cache(cache_key, response_json, created_at, expires_at) VALUES (?, ?, ?, ?)
      ON CONFLICT(cache_key) DO UPDATE SET response_json = excluded.response_json, created_at = excluded.created_at, expires_at = excluded.expires_at`,
    [key, JSON.stringify(value), at, at + TUTOR_CACHE_TTL_MS]);
    // Expired rows are swept on write, bounded by the expiry index.
    await db.run('DELETE FROM tutor_cache WHERE expires_at <= ?', [at]);
  }

  async function help(request) {
    // The typed answer counts as the student's final line only when there is no
    // working; it is never verified, so it never excuses anything.
    const guard = buildGuard(request.question, {
      studentLines: request.studentWork.lines,
      verifiedLines: request.studentWork.verifiedLines
    });
    let model = null;
    for (let attempt = 0; attempt < 2; attempt += 1) {
      // Every model call is a paid call, the regeneration included.
      const overBudget = await consumePaidCall(db, { env });
      if (overBudget) {
        if (attempt === 0) return { refusal: overBudget };
        break;
      }
      const reply = await ask(request, { env });
      model = reply.model || model;
      const leaked = leakedExpressions(reply.message, guard, { prompt: request.question.prompt });
      if (reply.message && !reply.revealsAnswer && !leaked.length) {
        return {
          tutor: {
            level: request.level, message: reply.message, referencesStepIndex: reply.referencesStepIndex,
            source: 'model', guarded: attempt > 0, model
          }
        };
      }
    }
    // Two strikes: the authored hint, which a person wrote and reviewed.
    return {
      tutor: {
        level: request.level, message: deterministicHelp(request), referencesStepIndex: -1,
        source: 'fallback', guarded: true, reason: 'TUTOR_ANSWER_GUARD', model
      }
    };
  }

  async function walkthrough(request) {
    const overBudget = await consumePaidCall(db, { env });
    if (overBudget) return { refusal: overBudget };
    const reply = await ask(request, { env });
    const spans = solutionSpans(request.question);
    let rejected = 0;
    const captions = request.captions.map((caption, index) => {
      const proposed = reply.captions?.get?.(index);
      if (proposed && proposed.length <= MAX_CAPTION_CHARS && captionWordingOk(proposed, caption.text, spans)) {
        return { id: caption.id, text: proposed, source: 'model' };
      }
      if (proposed) rejected += 1;
      return { id: caption.id, text: caption.text, source: 'deterministic' };
    });
    return {
      tutor: {
        level: 'walkthrough', captions, rejected,
        source: captions.some(c => c.source === 'model') ? 'model' : 'fallback', model: reply.model || null
      }
    };
  }

  router.post('/help',
    requireSession(db),
    requireVerifiedEmail,
    rateLimit(db, 'tutor-help', TUTOR_RATE_LIMIT),
    async (req, res) => {
      let size = Infinity;
      try { size = Buffer.byteLength(JSON.stringify(req.body ?? null)); } catch { /* refused below */ }
      if (size > MAX_TUTOR_BODY_BYTES) {
        return res.status(413).json({ error: { code: 'TUTOR_REQUEST_TOO_LARGE', message: `A tutor request is at most ${MAX_TUTOR_BODY_BYTES} bytes.` } });
      }
      const checked = validateTutorRequest(req.body);
      if (!checked.ok) return res.status(checked.status).json({ error: { code: checked.code, message: checked.message } });

      const at = now();
      const grounded = await groundIssued(db, req.platformSession.account_id, checked.request, at);
      if (!grounded.ok) return res.status(grounded.status).json({ error: { code: grounded.code, message: grounded.message } });
      const request = grounded.request;
      const key = tutorCacheKey(request, cacheScope(req.platformSession.account_id));
      const hit = await cached(key, at);
      if (hit) return res.json({ tutor: { ...hit, cached: true } });

      if (!providerConfig(env).configured) {
        return res.status(503).json({ error: { code: 'TUTOR_NOT_CONFIGURED', message: 'The AI tutor is not available on this deployment.' } });
      }

      // Per-account daily allowance, counted per request that reaches the model.
      const accountId = req.platformSession.account_id;
      const daily = await consumeRateLimit(db, `tutor-day:${sha256(accountId).slice(0, 24)}`,
        { limit: await tutorDailyLimit(db, accountId, env), windowMs: 24 * 60 * 60 * 1000 }, at);
      if (!daily.allowed) {
        res.set('RateLimit-Reset', String(Math.ceil(daily.resetAt / 1000)));
        return res.status(429).json({ error: { code: 'TUTOR_DAILY_LIMIT', message: "You have used today's tutor help. The question's own hints still work.", retryable: true } });
      }

      try {
        const outcome = request.level === 'walkthrough' ? await walkthrough(request) : await help(request);
        if (outcome.refusal) return refusePaidCall(res, outcome.refusal);
        await remember(key, outcome.tutor, at);
        res.json({ tutor: { ...outcome.tutor, cached: false } });
      } catch (error) {
        // Only the code is reported. No question, solution or student work is
        // logged or echoed: diagnostics stay privacy-safe.
        if (error instanceof TutorProviderError) {
          return res.status(error.status).json({ error: { code: error.code, message: error.message, retryable: !!error.retryable } });
        }
        res.status(502).json({ error: { code: 'TUTOR_FAILED', message: 'The tutor could not help this time.', retryable: true } });
      }
    });

  // ── Streaming ──────────────────────────────────────────────────────────────

  /** Every refusal a stream can meet happens here, as ordinary JSON, before any SSE byte. */
  async function admitStream(req, res) {
    let size = Infinity;
    try { size = Buffer.byteLength(JSON.stringify(req.body ?? null)); } catch { /* refused below */ }
    if (size > MAX_TUTOR_BODY_BYTES) {
      res.status(413).json({ error: { code: 'TUTOR_REQUEST_TOO_LARGE', message: `A tutor request is at most ${MAX_TUTOR_BODY_BYTES} bytes.` } });
      return null;
    }
    const checked = validateTutorRequest(req.body);
    if (!checked.ok) { res.status(checked.status).json({ error: { code: checked.code, message: checked.message } }); return null; }
    if (!TUTOR_STREAM_LEVELS.includes(checked.request.level)) {
      res.status(400).json({ error: { code: 'TUTOR_BODY_INVALID', message: `Only ${TUTOR_STREAM_LEVELS.join(', ')} are streamed; a walkthrough uses /help.` } });
      return null;
    }
    const at = now();
    const accountId = req.platformSession.account_id;
    const grounded = await groundIssued(db, accountId, checked.request, at);
    if (!grounded.ok) { res.status(grounded.status).json({ error: { code: grounded.code, message: grounded.message } }); return null; }
    const request = grounded.request;
    const key = tutorCacheKey(request, cacheScope(accountId));
    const hit = await cached(key, at);
    if (hit) return { request, key, at, hit };

    if (!providerConfig(env).configured) {
      res.status(503).json({ error: { code: 'TUTOR_NOT_CONFIGURED', message: 'The AI tutor is not available on this deployment.' } });
      return null;
    }
    // The same daily allowance as /help, and the same shared ceiling: a
    // streamed turn costs what a turn costs, and is refused before the provider
    // is contacted.
    const daily = await consumeRateLimit(db, `tutor-day:${sha256(accountId).slice(0, 24)}`,
      { limit: await tutorDailyLimit(db, accountId, env), windowMs: 24 * 60 * 60 * 1000 }, at);
    if (!daily.allowed) {
      res.set('RateLimit-Reset', String(Math.ceil(daily.resetAt / 1000)));
      res.status(429).json({ error: { code: 'TUTOR_DAILY_LIMIT', message: "You have used today's tutor help. The question's own hints still work.", retryable: true } });
      return null;
    }
    const overBudget = await consumePaidCall(db, { env });
    if (overBudget) { refusePaidCall(res, overBudget); return null; }
    return { request, key, at, hit: null };
  }

  function openStream(res) {
    res.status(200);
    res.set({
      'Content-Type': 'text/event-stream; charset=utf-8',
      'Cache-Control': 'no-store, no-transform',
      Connection: 'keep-alive',
      'X-Accel-Buffering': 'no'
    });
    res.flushHeaders();
    return (event, data) => {
      if (res.writableEnded || res.destroyed) return;
      res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
      // compression() buffers; flush pushes each event to the wire now.
      if (typeof res.flush === 'function') res.flush();
    };
  }

  router.post('/stream',
    requireSession(db),
    requireVerifiedEmail,
    rateLimit(db, 'tutor-stream', TUTOR_STREAM_RATE_LIMIT),
    async (req, res) => {
      const admitted = await admitStream(req, res);
      if (!admitted) return;
      const { request, key, at, hit } = admitted;
      const send = openStream(res);

      if (hit) {
        // A cached reply streams as one delta: same events, no spend.
        send('meta', { level: hit.level, source: hit.source, model: hit.model || null, cached: true });
        send('delta', { text: hit.message });
        send('done', { ...hit, cached: true });
        return res.end();
      }

      const sessionId = req.platformSession.id;
      const controller = new AbortController();
      const previous = openStreams.get(sessionId);
      if (previous) previous.abort('superseded');
      openStreams.set(sessionId, controller);
      const onClose = () => controller.abort('closed');
      req.on('close', onClose);

      const guard = buildGuard(request.question, { studentLines: request.studentWork.lines, verifiedLines: request.studentWork.verifiedLines });
      const gate = createReleaseGate(guard, { prompt: request.question.prompt, maxChars: MAX_STREAM_CHARS });
      const model = providerConfig(env).model;
      send('meta', { level: request.level, source: 'model', model, cached: false });

      const fallback = () => {
        // The authored hint, which a person wrote and reviewed. Not cached: the
        // model's reply was unusable and the next turn deserves a fresh one.
        send('fallback', { level: request.level, message: deterministicHelp(request), referencesStepIndex: -1, source: 'fallback', guarded: true, reason: 'TUTOR_ANSWER_GUARD', model });
      };

      try {
        let ended = false;
        for await (const delta of stream(request, { env, signal: controller.signal })) {
          if (controller.signal.aborted) break;
          const step = gate.push(delta);
          if (step.leaks.length) { fallback(); ended = true; break; }
          if (step.release) send('delta', { text: step.release });
          if (step.capped) break;
        }
        if (!ended && !controller.signal.aborted) {
          const last = gate.finish();
          if (last.leaks.length) fallback();
          else {
            if (last.release) send('delta', { text: last.release });
            const message = gate.released.trim();
            if (!message) fallback();
            else {
              const tutor = { level: request.level, message, referencesStepIndex: -1, source: 'model', guarded: false, model };
              await remember(key, tutor, at);
              send('done', { ...tutor, cached: false });
            }
          }
        } else if (controller.signal.aborted && controller.signal.reason === 'superseded') {
          send('error', { code: 'TUTOR_STREAM_SUPERSEDED', message: 'A newer question replaced this one.', retryable: false });
        }
      } catch (error) {
        // Codes only: no question, solution or student work is logged or echoed.
        if (controller.signal.aborted && controller.signal.reason === 'superseded') {
          send('error', { code: 'TUTOR_STREAM_SUPERSEDED', message: 'A newer question replaced this one.', retryable: false });
        } else if (error instanceof TutorProviderError) {
          send('error', { code: error.code, message: error.message, retryable: !!error.retryable });
        } else {
          send('error', { code: 'TUTOR_FAILED', message: 'The tutor could not help this time.', retryable: true });
        }
      } finally {
        req.off('close', onClose);
        if (openStreams.get(sessionId) === controller) openStreams.delete(sessionId);
        res.end();
      }
    });

  return router;
}
